CREATE TABLE `situation_reports` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `PI_DateOfInterview` date NOT NULL,
  `PI_ReportingPeriodStart` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_ReportingPeriodEnd` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_Location` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_IFMName` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_NameOfInterviewee` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_Gender` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_TitleOfInterviewee` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_Education` varchar(140) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_AgeOfInterviewee` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_ModeOfInterview` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PI_GPS` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_CN_CellServiceAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_CN_CellServiceAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_CN_CellServiceCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_CN_CellServiceCostChange` tinyint(4) NOT NULL,
  `CSS_CN_InternetAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_CN_InternetAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_CN_InternetCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_CN_InternetCostChange` tinyint(4) NOT NULL,
  `CSS_FE_PetrolAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_FE_PetrolAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_FE_PetrolCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_FE_PetrolCostChange` tinyint(4) NOT NULL,
  `CSS_FE_DieselAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_FE_DieselAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_FE_DieselCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_FE_DieselCostChange` tinyint(4) NOT NULL,
  `CSS_FE_CookingGasCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_FE_CookingGasCostChange` tinyint(4) NOT NULL,
  `CSS_FE_CookingGasAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_FE_CookingGasAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_LT_SharedTaxiCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_LT_SharedTaxiCostChange` tinyint(4) NOT NULL,
  `CSS_LT_SharedTaxiAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_LT_SharedTaxiAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_LT_TaxiCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_LT_TaxiCostChange` tinyint(4) NOT NULL,
  `CSS_LT_TaxiAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_LT_TaxiAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_LT_BusesCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_LT_BusesCostChange` tinyint(4) NOT NULL,
  `CSS_LT_BusesAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_LT_BusesAvailabilityChange` tinyint(4) NOT NULL,
  `CSS_HA_HousingRentalCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_HA_HousingRentalCostChange` tinyint(4) NOT NULL,
  `CSS_HA_HousingRentalAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CSS_HA_HousingRentalAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_ImmunizationsCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_ImmunizationsCostChange` tinyint(4) NOT NULL,
  `ES_HS_ImmunizationsAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_ImmunizationsAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_EmergencyCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_EmergencyCostChange` tinyint(4) NOT NULL,
  `ES_HS_EmergencyAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_EmergencyAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_MaternalEmergencyCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_MaternalEmergencyCostChange` tinyint(4) NOT NULL,
  `ES_HS_MaternalEmergencyAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_MaternalEmergencyAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_PrimaryHealthCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_PrimaryHealthCostChange` tinyint(4) NOT NULL,
  `ES_HS_PrimaryHealthAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_PrimaryHealthAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_MedicineCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_MedicineCostChange` tinyint(4) NOT NULL,
  `ES_HS_MedicineAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_MedicineAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_PublicHospitalsCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_PublicHospitalsCostChange` tinyint(4) NOT NULL,
  `ES_HS_PublicHospitalsAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_PublicHospitalsAvailabilityChange` tinyint(4) NOT NULL,
  `ES_HS_PrivateHospitalsCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_PrivateHospitalsCostChange` tinyint(4) NOT NULL,
  `ES_HS_PrivateHospitalsAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_HS_PrivateHospitalsAvailabilityChange` tinyint(4) NOT NULL,
  `ES_E_PublicPrimarySchoolCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PublicPrimarySchoolCostChange` tinyint(4) NOT NULL,
  `ES_E_PublicPrimarySchoolAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PublicPrimarySchoolAvailabilityChange` tinyint(4) NOT NULL,
  `ES_E_PrivatePrimarySchoolCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PrivatePrimarySchoolCostChange` tinyint(4) NOT NULL,
  `ES_E_PrivatePrimarySchoolAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PrivatePrimarySchoolAvailabilityChange` tinyint(4) NOT NULL,
  `ES_E_PublicSecondarySchoolCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PublicSecondarySchoolCostChange` tinyint(4) NOT NULL,
  `ES_E_PublicSecondarySchoolAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PublicSecondarySchoolAvailabilityChange` tinyint(4) NOT NULL,
  `ES_E_PrivateSecondarySchoolCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PrivateSecondarySchoolCostChange` tinyint(4) NOT NULL,
  `ES_E_PrivateSecondarySchoolAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PrivateSecondarySchoolAvailabilityChange` tinyint(4) NOT NULL,
  `ES_E_PublicPostSecondaryCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PublicPostSecondaryCostChange` tinyint(4) NOT NULL,
  `ES_E_PublicPostSecondaryAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PublicPostSecondaryAvailabilityChange` tinyint(4) NOT NULL,
  `ES_E_PrivatePostSecondaryCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PrivatePostSecondaryCostChange` tinyint(4) NOT NULL,
  `ES_E_PrivatePostSecondaryAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_E_PrivatePostSecondaryAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_MunicipalElectricityCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_MunicipalElectricityCostChange` tinyint(4) NOT NULL,
  `ES_GS_MunicipalElectricityAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_MunicipalElectricityAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_PrivateElectricityCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_PrivateElectricityCostChange` tinyint(4) NOT NULL,
  `ES_GS_PrivateElectricityAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_PrivateElectricityAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_MunicipalDrinkingCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_MunicipalDrinkingCostChange` tinyint(4) NOT NULL,
  `ES_GS_MunicipalDrinkingAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_MunicipalDrinkingAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_PrivateWaterCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_PrivateWaterCostChange` tinyint(4) NOT NULL,
  `ES_GS_PrivateWaterAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_PrivateWaterAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_GarbageCollectionCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_GarbageCollectionCostChange` tinyint(4) NOT NULL,
  `ES_GS_GarbageCollectionAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_GarbageCollectionAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_SewerageCost` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_SewerageCostChange` tinyint(4) NOT NULL,
  `ES_GS_SewerageAvailability` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_SewerageAvailabilityChange` tinyint(4) NOT NULL,
  `ES_GS_CivilServantSalaries` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_GS_CivilServantSalariesChange` tinyint(4) NOT NULL,
  `ES_SSN_SocialSecurityPayments` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_SSN_SocialSecurityPaymentsChange` tinyint(4) NOT NULL,
  `ES_SSN_RationCard` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_SSN_RationCardChange` tinyint(4) NOT NULL,
  `ES_SSN_CharitablePayments` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_SSN_CharitablePaymentsChange` tinyint(4) NOT NULL,
  `ES_SSN_SupportForIDPs` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ES_SSN_SupportForIDPsChange` tinyint(4) NOT NULL,
  `I_COPI_Transportation` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_COPI_TransportationChange` tinyint(4) NOT NULL,
  `I_COPI_Dams` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_COPI_DamsChange` tinyint(4) NOT NULL,
  `I_COPI_Roads` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_COPI_RoadsChange` tinyint(4) NOT NULL,
  `I_COPI_Airport` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_COPI_AirportChange` tinyint(4) NOT NULL,
  `I_COPI_Petroleum` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_COPI_PetroleumChange` tinyint(4) NOT NULL,
  `I_DTPSI_Electricity` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_ElectricityChange` tinyint(4) NOT NULL,
  `I_DTPSI_WaterTreatment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_WaterTreatmentChange` tinyint(4) NOT NULL,
  `I_DTPSI_WaterNetwork` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_WaterNetworkChange` tinyint(4) NOT NULL,
  `I_DTPSI_SewageTreatment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_SewageTreatmentChange` tinyint(4) NOT NULL,
  `I_DTPSI_SewageNetwork` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_SewageNetworkChange` tinyint(4) NOT NULL,
  `I_DTPSI_Government` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_GovernmentChange` tinyint(4) NOT NULL,
  `I_DTPSI_Schools` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_SchoolsChange` tinyint(4) NOT NULL,
  `I_DTPSI_Health` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTPSI_HealthChange` tinyint(4) NOT NULL,
  `I_DTCI_PublicMarket` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTCI_PublicMarketChange` tinyint(4) NOT NULL,
  `I_DTCI_Shops` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTCI_ShopsChange` tinyint(4) NOT NULL,
  `I_DTCI_Banks` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTCI_BanksChange` tinyint(4) NOT NULL,
  `I_DTCI_GovernmentStores` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTCI_GovernmentStoresChange` tinyint(4) NOT NULL,
  `I_DTCI_Factories` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTCI_FactoriesChange` tinyint(4) NOT NULL,
  `I_DTCI_OfficeBuildings` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTCI_OfficeBuildingsChange` tinyint(4) NOT NULL,
  `I_DTAI_IrrigationChannels` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTAI_IrrigationChannelsChange` tinyint(4) NOT NULL,
  `I_DTAI_FarmEquipment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTAI_FarmEquipmentChange` tinyint(4) NOT NULL,
  `I_DTAI_FoodStorage` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTAI_FoodStorageChange` tinyint(4) NOT NULL,
  `I_DTAI_Livestock` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTAI_LivestockChange` tinyint(4) NOT NULL,
  `I_DTAI_Dairy` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTAI_DairyChange` tinyint(4) NOT NULL,
  `I_DTAI_Greenhouses` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTAI_GreenhousesChange` tinyint(4) NOT NULL,
  `I_DTHI_ApartmentBuildings` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTHI_ApartmentBuildingsChange` tinyint(4) NOT NULL,
  `I_DTHI_SmallVillas` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `I_DTHI_SmallVillasChange` tinyint(4) NOT NULL,
  `ESS_BankService` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ESS_BankServiceChange` tinyint(4) NOT NULL,
  `ESS_IraqStockExchange` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ESS_IraqStockExchangeChange` tinyint(4) NOT NULL,
  `ESS_USD_IQD_RateOFFICIAL` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ESS_USD_IQD_RateOFFICIALChange` tinyint(4) NOT NULL,
  `ESS_USD_IQD_RateUNOFFICIAL` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ESS_USD_IQD_RateUNOFFICIALChange` tinyint(4) NOT NULL,
  `SI_FONC_weddings` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_FONC_weddingsChange` tinyint(4) NOT NULL,
  `SI_FONC_GraduationCeremonies` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_FONC_GraduationCeremoniesChange` tinyint(4) NOT NULL,
  `SI_FONC_Festivals` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_FONC_FestivalsChange` tinyint(4) NOT NULL,
  `SI_FONC_OpeningCeremonies` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_FONC_OpeningCeremoniesChange` tinyint(4) NOT NULL,
  `SI_FONC_FridayPicnics` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_FONC_FridayPicnicsChange` tinyint(4) NOT NULL,
  `SI_RP_ReligiousCelebrations` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_RP_ReligiousCelebrationsChange` tinyint(4) NOT NULL,
  `SI_RP_FridayPrayer` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_RP_FridayPrayerChange` tinyint(4) NOT NULL,
  `SI_YE_SportsEvents` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_YE_SportsEventsChange` tinyint(4) NOT NULL,
  `SI_YE_YouthLed` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_YE_YouthLedChange` tinyint(4) NOT NULL,
  `SI_YE_OtherPublic` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SI_YE_OtherPublicChange` tinyint(4) NOT NULL,
  `GC_ProfileOfKeyGovernment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `GC_ProfileOfKeyGovernmentChange` tinyint(4) NOT NULL,
  `GC_ElectionsOrChanges` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `GC_ElectionsOrChangesChange` tinyint(4) NOT NULL,
  `GC_ProgressOnGovernment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `GC_ProgressOnGovernmentChange` tinyint(4) NOT NULL,
  `GC_PublicDemonstrations` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `GC_PublicDemonstrationsChange` tinyint(4) NOT NULL,
  `GC_FunctionalityLegalSystem` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `GC_FunctionalityLegalSystemChange` tinyint(4) NOT NULL,
  `GC_FunctionalityLocalCouncil` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `GC_FunctionalityLocalCouncilChange` tinyint(4) NOT NULL,
  `HC_Movement` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `HC_MovementChange` tinyint(4) NOT NULL,
  `HC_Humanitarian` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `HC_HumanitarianChange` tinyint(4) NOT NULL,
  `HC_NaturalDisasters` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `HC_NaturalDisastersChange` tinyint(4) NOT NULL,
  `HC_SectarianIncidents` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `HC_SectarianIncidentsChange` tinyint(4) NOT NULL,
  `HC_CleanUp` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `HC_CleanUpChange` tinyint(4) NOT NULL,
  `CC_AttacksAgainstKeyPoliticalFigures` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_AttacksAgainstKeyPoliticalFiguresChange` tinyint(4) NOT NULL,
  `CC_AttacksAgainstPoliceOrSecurityForces` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_AttacksAgainstPoliceOrSecurityForcesChange` tinyint(4) NOT NULL,
  `CC_PresenceOfArmedMilitias` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_PresenceOfArmedMilitiasChange` tinyint(4) NOT NULL,
  `CC_FunctionalityOfPoliceOrSecurityForces` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_FunctionalityOfPoliceOrSecurityForcesChange` tinyint(4) NOT NULL,
  `CC_CurfewOrGovernmentIraq` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_CurfewOrGovernmentIraqChange` tinyint(4) NOT NULL,
  `CC_IrregularCheckpointsRoadblocks` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_IrregularCheckpointsRoadblocksChange` tinyint(4) NOT NULL,
  `CC_TerroristIncidents` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_TerroristIncidentsChange` tinyint(4) NOT NULL,
  `CC_CriminalActivity` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_CriminalActivityChange` tinyint(4) NOT NULL,
  `CC_GenderOrSexualBasedViolence` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_GenderOrSexualBasedViolenceChange` tinyint(4) NOT NULL,
  `CC_Other` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `CC_OtherChange` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `situation_reports_user_id_index` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;